import type { Ticket, Message, Product } from "./types"

export const mockTickets: Ticket[] = [
  {
    id: "1",
    code: "FBT-2025-00124",
    subject: "POS Integration not syncing menu items",
    restaurant: "Bella Italia Downtown",
    product: "POS Integration",
    status: "Open",
    clientStatus: "Troubleshooting",
    priority: "High",
    assignedTo: "John Doe",
    lastUpdated: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    unread: true,
    createdViaEmail: false,
    tags: ["integration", "menu-sync", "urgent"],
    timeline: [
      {
        id: "t1",
        type: "created",
        description: "Ticket created",
        timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
        actor: "Restaurant Owner",
      },
      {
        id: "t2",
        type: "assigned",
        description: "Assigned to John Doe",
        timestamp: new Date(Date.now() - 1000 * 60 * 115).toISOString(),
        actor: "System",
      },
      {
        id: "t3",
        type: "status_changed",
        description: "Status changed to Troubleshooting",
        timestamp: new Date(Date.now() - 1000 * 60 * 110).toISOString(),
        actor: "John Doe",
      },
    ],
  },
  {
    id: "2",
    code: "FBT-2025-00123",
    subject: "Unable to generate weekly sales report",
    restaurant: "Sushi Express",
    product: "Analytics Dashboard",
    status: "Open",
    clientStatus: "Awaiting Client",
    priority: "Medium",
    assignedTo: "Jane Smith",
    lastUpdated: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    unread: false,
    createdViaEmail: true,
    tags: ["reporting", "analytics"],
    timeline: [
      {
        id: "t1",
        type: "created",
        description: "Ticket created via email",
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
        actor: "Manager",
      },
      {
        id: "t2",
        type: "assigned",
        description: "Assigned to Jane Smith",
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
        actor: "System",
      },
    ],
  },
  {
    id: "3",
    code: "FBT-2025-00122",
    subject: "Staff member cannot access manager dashboard",
    restaurant: "Taco Haven",
    product: "Staff Management",
    status: "Open",
    clientStatus: "Open Response Pending",
    priority: "Critical",
    assignedTo: "John Doe",
    lastUpdated: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    unread: true,
    createdViaEmail: false,
    tags: ["access-issue", "urgent"],
    timeline: [
      {
        id: "t1",
        type: "created",
        description: "Ticket created",
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
        actor: "Owner",
      },
    ],
  },
  {
    id: "4",
    code: "FBT-2025-00121",
    subject: "Request for custom reporting feature",
    restaurant: "Green Bowl Cafe",
    product: "Custom Features",
    status: "Open",
    clientStatus: "Open Response Pending",
    priority: "Low",
    assignedTo: "Mike Johnson",
    lastUpdated: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    unread: false,
    createdViaEmail: true,
    tags: ["feature-request"],
    timeline: [
      {
        id: "t1",
        type: "created",
        description: "Ticket created via email",
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
        actor: "Manager",
      },
    ],
  },
  {
    id: "5",
    code: "FBT-2025-00120",
    subject: "Payment processing delay during peak hours",
    restaurant: "Burger Palace",
    product: "Payment Gateway",
    status: "Closed",
    clientStatus: "Resolved",
    priority: "High",
    assignedTo: "Jane Smith",
    lastUpdated: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    unread: false,
    createdViaEmail: false,
    tags: ["billing", "payment-issue"],
    timeline: [
      {
        id: "t1",
        type: "created",
        description: "Ticket created",
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
        actor: "Owner",
      },
      {
        id: "t2",
        type: "resolved",
        description: "Issue resolved",
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
        actor: "Jane Smith",
      },
    ],
    closureSummary: {
      clientSummary:
        "We identified a configuration issue with your payment processor during high-traffic periods. The issue has been resolved by optimizing the connection pool settings. Your payment processing should now handle peak hours smoothly.",
      internalSummary:
        "Root cause: Payment gateway connection pool was undersized for their traffic volume. Fixed by increasing pool size from 10 to 50 connections and implementing better retry logic. Monitored for 24hrs post-fix with no issues.",
      closedAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
      closedBy: "Jane Smith",
    },
  },
  {
    id: "6",
    code: "FBT-2025-00119",
    subject: "Online ordering widget not displaying correctly",
    restaurant: "Pizza Corner",
    product: "Online Ordering",
    status: "Open",
    clientStatus: "Troubleshooting",
    priority: "Medium",
    assignedTo: "John Doe",
    lastUpdated: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    unread: true,
    createdViaEmail: false,
    tags: ["ui-bug", "online-ordering"],
    timeline: [
      {
        id: "t1",
        type: "created",
        description: "Ticket created",
        timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
        actor: "Manager",
      },
      {
        id: "t2",
        type: "assigned",
        description: "Assigned to John Doe",
        timestamp: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
        actor: "System",
      },
    ],
  },
]

export const mockMessages: Message[] = [
  {
    id: "m1",
    ticketId: "1",
    content:
      "Hi, our POS system stopped syncing menu items about 2 hours ago. We just added new seasonal items but they are not showing up in the system.",
    sender: "Restaurant Owner",
    senderRole: "client",
    timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    isInternal: false,
    reactions: [{ emoji: "👍", users: ["John Doe (CS)"], count: 1 }],
  },
  {
    id: "m2",
    ticketId: "1",
    content: "Ticket assigned to John Doe",
    sender: "System",
    senderRole: "system",
    timestamp: new Date(Date.now() - 1000 * 60 * 115).toISOString(),
    isInternal: false,
  },
  {
    id: "m3",
    ticketId: "1",
    content:
      "Hello! Thank you for reaching out. I can see the sync issue. Let me check your POS integration settings and API logs.",
    sender: "John Doe (CS)",
    senderRole: "cs",
    timestamp: new Date(Date.now() - 1000 * 60 * 110).toISOString(),
    isInternal: false,
  },
  {
    id: "m4",
    ticketId: "1",
    content:
      "Found API rate limit exceeded errors in logs. Need to check with engineering team about increasing limits for this account.",
    sender: "John Doe (CS)",
    senderRole: "cs",
    timestamp: new Date(Date.now() - 1000 * 60 * 105).toISOString(),
    isInternal: true,
  },
  {
    id: "m5",
    ticketId: "1",
    content:
      "I found the issue - your POS provider updated their API yesterday and we need to adjust our integration. I am working on a fix now and will update you within the next 30 minutes.",
    sender: "John Doe (CS)",
    senderRole: "cs",
    timestamp: new Date(Date.now() - 1000 * 60 * 100).toISOString(),
    isInternal: false,
    reactions: [
      { emoji: "🚀", users: ["Restaurant Owner"], count: 1 },
      { emoji: "❤️", users: ["Restaurant Owner", "John Doe (CS)"], count: 2 },
    ],
  },
  {
    id: "m6",
    ticketId: "1",
    content: "That would be great, thank you! We need this fixed before dinner rush at 6pm.",
    sender: "Restaurant Owner",
    senderRole: "client",
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    isInternal: false,
  },
  {
    id: "m7",
    ticketId: "2",
    content:
      'When I try to generate our weekly sales report, I get an error message saying "Data unavailable". This started happening since yesterday.',
    sender: "Manager",
    senderRole: "client",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    isInternal: false,
  },
  {
    id: "m8",
    ticketId: "2",
    content:
      "Hi there! Can you please try clearing your browser cache and attempting to generate the report again? Also, could you let me know which date range you are trying to pull?",
    sender: "Jane Smith (CS)",
    senderRole: "cs",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    isInternal: false,
  },
  {
    id: "m9",
    ticketId: "3",
    content:
      "URGENT: One of our managers cannot access the manager dashboard. They just get a blank screen after logging in. This is affecting our operations!",
    sender: "Owner",
    senderRole: "client",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    isInternal: false,
  },
]

export const mockProducts: Product[] = [
  {
    id: "pos",
    name: "POS Integration",
    description: "Point of sale system integration and syncing",
    icon: "💳",
  },
  {
    id: "analytics",
    name: "Analytics Dashboard",
    description: "Sales reports and business insights",
    icon: "📊",
  },
  {
    id: "staff",
    name: "Staff Management",
    description: "Employee scheduling and permissions",
    icon: "👥",
  },
  {
    id: "ordering",
    name: "Online Ordering",
    description: "Customer ordering system and widgets",
    icon: "🛒",
  },
  {
    id: "payment",
    name: "Payment Gateway",
    description: "Payment processing and transactions",
    icon: "💰",
  },
  {
    id: "custom",
    name: "Custom Features",
    description: "Special requests and custom development",
    icon: "⚙️",
  },
]

export const availableTags = [
  "billing",
  "menu-sync",
  "device-offline",
  "integration",
  "bug",
  "feature-request",
  "urgent",
  "reporting",
  "analytics",
  "access-issue",
  "payment-issue",
  "ui-bug",
  "online-ordering",
]
